#!/bin/sh

set -eu

status=1
targetpath=/usr/lib/adobe-flashplugin/libpepflashplayer-amd64.so

apt-get install --download-only -y adobe-flashplugin:amd64

for deb in /var/cache/apt/archives/adobe-flashplugin_*_amd64.deb; do
  test -e "$deb" || continue

  dpkg-deb --fsys-tarfile "$deb" \
    | tar -Ox ./usr/lib/adobe-flashplugin/libpepflashplayer.so \
    > "${targetpath}.tmp"

  if [ -s "${targetpath}.tmp" ]; then
    mv "${targetpath}.tmp" "$targetpath"
    status=0
    break
  else
    echo "Failed to extract libpepflashplayer.so from $deb" >&2
    rm -f "${targetpath}.tmp"
  fi
done

if [ "$status" -eq 1 ]; then
  echo 'Could not find flashplugin from any adobe-flashplugin package' >&2
fi

exit $status
