#!/bin/sh

# This is a script for doing dynamic DNS updates.  Both forward and reverse
# records are updated.  It just requests puavo-rest to do the actual updates,
# passing the necessary DNS-key.
#
# Internal networks should be in the 10.0.0.0/8 range for reverse mappings
# to work (maybe probably? -- this is how we use it anyway).
#
# Key can be generated using the command:
#
# $ dnssec-keygen -a HMAC-MD5 -b 128 -n HOST puavo-key
# Kpuavo-key.+157+10879
#
# $ cat Kpuavo-key.+157+10879.private
# Private-key-format: v1.3
# Algorithm: 157 (HMAC_MD5)
# Key: n0FG8QLzMC6vKhqW61NWeQ==
# Bits: AAA=
# Created: 20130114153920
# Publish: 20130114153920
# Activate: 20130114153920
#
# Bind configuration (/etc/bind/named.conf.local) should look something 
# like this:
#
# key "puavo-updater" {
#        algorithm hmac-md5;
#        secret "n0FG8QLzMC6vKhqW61NWeQ==";
# };
#
# zone "example.org" {
#         type master;
#         file "/var/lib/bind/puavo_domain";
#         update-policy {
#                 grant puavo-updater zonesub ANY;
#         };
# };
#
# zone "246.10.in-addr.arpa" {
#         type master;
#         file "/var/lib/bind/puavo_domain_reverse";
#         update-policy {
#                 grant puavo-updater zonesub ANY;
#         };
# };
#
#

# XXX should use --ca-cert and such!

set -eu

type=$1
client_mac=$2
client_ip=$3
subdomain=$4
api_server=${5:-}

if [ -z "$api_server" ]; then
  api_server=$(puavo-resolve-api-server)
fi

nsupdate_keyfile_path='/etc/dhcp/ddns-keys/nsupdate.key'

# XXX Should this be simpler?  Maybe less parsing for this script?

key_name=$(awk '$1 == "key" {
             gsub(/^"/, "", $2); gsub(/"$/, "", $2); print $2; exit(0)
           }' "$nsupdate_keyfile_path")
key_secret=$(awk '$1 == "secret" {
               gsub(/^"/, "", $2); gsub(/";?$/, "", $2); print $2; exit(0)
             }' "$nsupdate_keyfile_path")

if [ -z "$key_name" ]; then
  echo 'Could not read key name from /etc/dhcp/ddns-keys/nsupdate.key' >&2
  exit 1
fi

if [ -z "$key_secret" ]; then
  echo 'Could not read secret from /etc/dhcp/ddns-keys/nsupdate.key' >&2
  exit 1
fi

printf %s "$key_secret" \
  | curl -X POST                                   \
         --cacert /etc/puavo/certs/rootca.pem      \
         --header      'Authorization: Bootserver' \
         --form        'key_secret=<-'             \
         --form-string "key_name=${key_name}"      \
         --form-string "type=${type}"              \
         --form-string "client_mac=${client_mac}"  \
         --form-string "client_ip=${client_ip}"    \
         --form-string "subdomain=${subdomain}"    \
         "${api_server}/v3/bootserver_dns_update"
